################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
# Laptop monitor
monitor=eDP-1, disable

# External MSI monitor forced to 240Hz
monitor=DP-1, 1920x1080@239.96, 1920x0, 1, vrr, 1
