################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
# El monitor de la laptop
monitor=eDP-1, disable

# El monitor MSI externo forzado a 240Hz
monitor=DP-1, 1920x1080@239.96, 1920x0, 1, vrr, 1
