const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const scope = {};
vm.createContext(scope);
vm.runInContext(fs.readFileSync(__dirname + '/../Singletons/MediaSource.js', 'utf8').replace(/^\.pragma library\s*/, ''), scope);
const describe = scope.describe;
assert.equal(describe('Spotify', 'spotify', '', '').label, 'Spotify');
assert.equal(describe('Chromium', 'chromium', '', 'https://music.youtube.com/watch?v=1').music, true);
assert.equal(describe('Firefox', 'firefox', '', 'https://www.youtube.com/watch?v=1').music, false);
assert.equal(describe('Firefox', 'firefox', '', 'https://music.apple.com/us/album/1').label, 'Apple Music');
assert.equal(describe('Cider', 'sh.cider.Cider', '', '').music, true);
assert.equal(describe('Elisa', 'org.kde.elisa', '', '').music, true);
assert.equal(describe('VLC', 'vlc', '', 'file:///video.mp4').music, false);
assert.equal(describe('Chromium', 'chromium', '', '').music, false);
assert.equal(describe('Firefox', 'firefox', '', 'https://music.youtube.com.evil.test/watch').music, false);
assert.equal(describe('Firefox', 'firefox', '', 'https://example.com/?url=music.apple.com').music, false);
assert.equal(describe('Firefox', 'firefox', '', 'https://open.spotify.com/track/1').icon, 'spotify');
console.log('PASS: music services, native players, browser fallback, exact URL hosts');
