include ~/.cache/wal/colors-kitty.conf

# Fuente
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
font_size        12.0

# Transparencia y blur
background_opacity 0.65
background_blur    128

# Padding interior
window_padding_width 12

# Sin decoraciones de ventana
hide_window_decorations yes

# Cursor
cursor_shape           block
cursor_blink_interval 0

# Silenciar el bell (el pitido por defecto al llegar al tope del scrollback es molesto)
enable_audio_bell no

# Scrollback
scrollback_lines 10000

# Tabs bonitos
tab_bar_style                 powerline
tab_powerline_style           slanted
tab_bar_min_tabs              2
tab_bar_edge                  bottom
active_tab_font_style         bold
inactive_tab_font_style       normal

sync_to_monitor no

# Performance
repaint_delay 8
input_delay   3
cursor_trail  7
