include ~/.cache/wal/colors-kitty.conf

# Font
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
font_size        12.0

# Transparency & blur
background_opacity 0.65
background_blur    128

# Inner padding
window_padding_width 12

# No window decorations
hide_window_decorations yes

# Cursor
cursor_shape           block
cursor_blink_interval 0

# Silence the bell (the default beep on hitting the scrollback limit is annoying)
enable_audio_bell no

# Scrollback
scrollback_lines 10000

# Pretty tabs
tab_bar_style                 powerline
tab_powerline_style           slanted
tab_bar_min_tabs              2
tab_bar_edge                  bottom
active_tab_font_style         bold
inactive_tab_font_style       normal

sync_to_monitor no

# Performance
repaint_delay 8
input_delay   3
cursor_trail  7
